server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cy_lab4
    username: root
    password: zl304036
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
